# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Wearables' do
  use_frameworks! :linkage => :static
   $RNFirebaseAsStaticFramework = true
   config = use_native_modules!
   pod 'ZendeskSDKMessaging'
   pod 'GoogleMLKit/ImageLabeling'
     pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'
   pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'
#   pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
#   pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
#   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
#   pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'
   
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'WearablesTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    
    installer.generated_projects.each do |project|
          if project.path.basename.to_s == 'Pods.xcodeproj'
            project.build_configurations.each do |config|
              config.build_settings['GENERATE_INFOPLIST_FILE'] = 'YES'
            end
            project.save
          else
            puts "Skipping project #{project.path.basename}"
          end
        end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
  
  
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
#      end
#    end
#  end
end
